# Generated by Django 4.2.4 on 2025-08-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.CharField(max_length=4)),
                ("cname", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
    ]
