# Generated by Django 4.2.4 on 2025-08-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_blogs_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blogs",
            new_name="Blog",
        ),
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
        migrations.RenameModel(
            old_name="Customers",
            new_name="Customer",
        ),
    ]
